language: c

addons:
  apt:
    packages: &default_packages
      - libfftw3-dev
      - libblas-dev
      - libpng-dev

matrix:
  include:
    - env: PARALLEL=1
      os: linux
      compiler: gcc-5
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - gcc-5
            - liblapacke-dev

    - env:
      os: linux
      compiler: gcc-5
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - gcc-5
            - liblapacke-dev
      script:
        - make test
        - make utest

    - env: OMP=0 CPPFLAGS=-fblocks LDFLAGS=-lBlocksRuntime CXX=clang++
      os: linux
      compiler: clang
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - *default_packages
            - liblapacke-dev
            - libblocksruntime-dev
      script:
        - make test
        - make utest

    - env: OMP=1
      os: linux
      compiler: gcc-5
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - gcc-5
            - liblapacke-dev
      script:
        - make test
        - make utest

    - env: NOLAPACKE=1
      os: linux
      compiler: gcc-5
      sudo: required
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - *default_packages
            - gcc-5
            - gfortran
            - liblapack-dev

script:
  - make bart
  - make all
