language: c

addons:
  apt:
    packages: &default_packages
      - libfftw3-dev
      - liblapack-dev
      - libpng-dev

matrix:
  include:
    - env: PARALLEL=1
      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - *default_packages

    - env: SLINK=1
      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - *default_packages
            - gfortran

    - env: OMP=0
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - *default_packages

    - env: CUDA=1 CUDA_BASE=/usr/local/cuda-7.5/
      os: linux
      compiler: clang-3.5
      sudo: required
      dist: trusty
      addons:
        apt:
          packages:
            - *default_packages
      before_install:
        - wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/cuda-repo-ubuntu1404_7.5-18_amd64.deb
        - sudo dpkg -i cuda-repo-ubuntu1404_7.5-18_amd64.deb
        - sudo apt-get update -qq
        - sudo apt-get install -qq clang-3.5
        - sudo apt-get install -qq --no-install-recommends cuda-drivers cuda-core-7.5 cuda-cudart-dev-7.5 cuda-cufft-dev-7.5 cuda-cublas-dev-7.5

    - os: osx
      compiler: gcc-4.7
      before_install:
        - brew update
        - brew install fftw gcc47

script:
  - make bart
  - make all
