.TH BART 1
.SH NAME
bart - Berkeley Advanced Reconstruction Tools 
.SH SYNOPSIS
.B bart
.IR command 
[\fB\-h\fR] ...
.SH DESCRIPTION
.B bart 
invokes a command from the Berkeley Advanced Reconstruction Tools.
.SH AUTHOR
Martin Uecker with the help of many others.
.SH SEE ALSO
.B https://mrirecon.github.io/bart/
