.TH BART 1
.SH NAME
bart - Berkeley Advanced Reconstruction Toolbox
.SH SYNOPSIS
.B bart
.IR command 
[\fB\-h\fR] ...
.SH DESCRIPTION
.B bart 
invokes a command from the Berkeley Advanced Reconstruction Toolbox.
.SH AUTHOR
BART Developer Team and Contributors.
.SH SEE ALSO
.B https://mrirecon.github.io/bart/
